Resources:
  SimpleInstanceCreate:
    Type: "AWS::EC2::Instance"
    Properties:
      AvailabilityZone: "ap-south-1a"
      ImageId: "ami-01a00762f46d584a1"
      InstanceType: "t2.micro"
      Tags:
        - Key: Name
          Value: Test_CFN_Server
