Resources:
  SimpleInstanceCreate:
    Type: "AWS::EC2::Instance"
    Properties:
      AvailabilityZone: "ap-south-1b"
      ImageId: "ami-01a00762f46d584a1"
      InstanceType: "t2.micro"
      Tags:
        - Key: Name
          Value: Test_CFN_Server

Resources:
  MySimpleS3Bucket:
    Type: AWS::S3::Bucket          
